# Generated by Django 6.0.6 on 2026-07-07 01:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='??')),
                ('category', models.CharField(choices=[('guide', '??'), ('news', '??'), ('story', '??'), ('tips', '???')], default='guide', max_length=20, verbose_name='??')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='??')),
                ('excerpt', models.TextField(blank=True, verbose_name='??')),
                ('content', models.TextField(blank=True, verbose_name='??')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='??URL')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='????')),
                ('is_published', models.BooleanField(default=True, verbose_name='??')),
                ('view_count', models.IntegerField(default=0, verbose_name='???')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='??')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='????')),
                ('country', models.CharField(max_length=100, verbose_name='??')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='??')),
                ('description', models.TextField(blank=True, verbose_name='??')),
                ('image', models.ImageField(blank=True, upload_to='destinations/', verbose_name='??')),
                ('image_url', models.CharField(blank=True, help_text='???????? images/gallery/g1.jpg', max_length=500, verbose_name='??URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('is_active', models.BooleanField(default=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '???',
                'verbose_name_plural': '???',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100, verbose_name='????')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='???')),
                ('origin_city', models.CharField(max_length=100, verbose_name='????')),
                ('destination_city', models.CharField(max_length=100, verbose_name='????')),
                ('departure_time', models.DateTimeField(verbose_name='????')),
                ('arrival_time', models.DateTimeField(verbose_name='????')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='??')),
                ('flight_type', models.CharField(choices=[('one_way', '??'), ('round_trip', '??')], default='one_way', max_length=20, verbose_name='????')),
                ('seats_available', models.IntegerField(default=100, verbose_name='??')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '??',
                'verbose_name_plural': '??',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='????')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='???')),
                ('description', models.TextField(blank=True, verbose_name='??')),
                ('discount', models.IntegerField(default=60, help_text='? 60 ??6?', verbose_name='????')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='???')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='??')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='??URL')),
                ('features', models.TextField(blank=True, help_text='????', verbose_name='??')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='????')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='??')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='????')),
                ('city', models.CharField(max_length=100, verbose_name='??')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='??')),
                ('stars', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='??')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='????')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='??')),
                ('review_count', models.IntegerField(default=0, verbose_name='???')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='??URL')),
                ('description', models.TextField(blank=True, verbose_name='??')),
                ('amenities', models.TextField(blank=True, help_text='????', verbose_name='????')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.destination', verbose_name='?????')),
            ],
            options={
                'verbose_name': '??',
                'verbose_name_plural': '??',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='????')),
                ('location', models.CharField(blank=True, help_text='???????', max_length=200, verbose_name='???')),
                ('avatar_url', models.CharField(blank=True, max_length=500, verbose_name='??URL')),
                ('quote', models.TextField(verbose_name='????')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='??')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='??')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='????')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='??')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='??')),
                ('duration_days', models.IntegerField(default=5, verbose_name='??')),
                ('duration_nights', models.IntegerField(default=6, verbose_name='??')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='??')),
                ('review_count', models.IntegerField(default=0, verbose_name='???')),
                ('image_url', models.CharField(blank=True, help_text='? images/packages/p1.jpg', max_length=500, verbose_name='??URL')),
                ('features', models.TextField(blank=True, help_text='?????????5??????', verbose_name='??')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='??')),
                ('is_active', models.BooleanField(default=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.destination', verbose_name='???')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-is_recommended', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('package', '????'), ('hotel', '??'), ('flight', '??')], max_length=20, verbose_name='????')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='??')),
                ('status', models.CharField(choices=[('pending', '???'), ('paid', '???'), ('confirmed', '???'), ('cancelled', '???'), ('completed', '???')], default='pending', max_length=20, verbose_name='??')),
                ('guest_count', models.IntegerField(default=1, verbose_name='??')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='??/????')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='??/????')),
                ('note', models.TextField(blank=True, verbose_name='??')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='??')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.flight', verbose_name='??')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.hotel', verbose_name='??')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.tourpackage', verbose_name='??')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['-created_at'],
            },
        ),
    ]
