# Generated by Django 6.0.6 on 2026-07-07 03:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('service_type', models.CharField(choices=[('insurance', '旅游保险'), ('pickup', '接机服务'), ('luggage', '行李托运'), ('visa', '签证代办'), ('guide', '私人导游')], max_length=20, verbose_name='服务类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '额外服务',
                'verbose_name_plural': '额外服务',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date'], 'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': '预订订单', 'verbose_name_plural': '预订订单'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': '目的地', 'verbose_name_plural': '目的地'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time'], 'verbose_name': '航班', 'verbose_name_plural': '航班'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': '酒店', 'verbose_name_plural': '酒店'},
        ),
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': '特惠活动', 'verbose_name_plural': '特惠活动'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': '邮件订阅', 'verbose_name_plural': '邮件订阅'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': '用户评价', 'verbose_name_plural': '用户评价'},
        ),
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-is_recommended', 'name'], 'verbose_name': '旅游套餐', 'verbose_name_plural': '旅游套餐'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.destination', verbose_name='相关目的地'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('guide', '攻略'), ('news', '资讯'), ('story', '游记'), ('tips', '小贴士')], default='guide', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='封面URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='发布'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('package', '旅游套餐'), ('hotel', '酒店'), ('flight', '航班'), ('custom', '定制套餐')], max_length=20, verbose_name='预订类型'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='入住/出发日期'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='退房/返回日期'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.flight', verbose_name='航班'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(default=1, verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.hotel', verbose_name='酒店'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.tourpackage', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='destinations/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.CharField(blank=True, help_text='静态图片路径，如 images/gallery/g1.jpg', max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='英文名称'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=100, verbose_name='航空公司'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='到达时间'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(verbose_name='出发时间'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(max_length=100, verbose_name='到达城市'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='航班号'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('one_way', '单程'), ('round_trip', '往返')], default='one_way', max_length=20, verbose_name='航班类型'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_city',
            field=models.CharField(max_length=100, verbose_name='出发城市'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(default=100, verbose_name='余票'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(blank=True, help_text='每行一项', verbose_name='设施服务'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.destination', verbose_name='所在目的地'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='酒店名称'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每晚价格'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='评价数'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='星级'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='discount',
            field=models.IntegerField(default=60, help_text='如 60 表示6折', verbose_name='折扣百分比'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='features',
            field=models.TextField(blank=True, verbose_name='特色'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(max_length=200, verbose_name='活动标题'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订阅时间'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='guest_name',
            field=models.CharField(max_length=100, verbose_name='游客姓名'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(verbose_name='评价内容'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.destination', verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_days',
            field=models.IntegerField(default=5, verbose_name='天数'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_nights',
            field=models.IntegerField(default=6, verbose_name='晚数'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='features',
            field=models.TextField(blank=True, help_text='每行一条特色', verbose_name='特色'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image_url',
            field=models.CharField(blank=True, help_text='如 images/packages/p1.jpg', max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='套餐名称'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='评价数'),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='travel_app.extraservice', verbose_name='额外服务'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_type', models.CharField(choices=[('package', '套餐'), ('hotel', '酒店'), ('flight', '航班'), ('blog', '攻略'), ('destination', '目的地')], max_length=20, verbose_name='收藏类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.blogpost')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.hotel')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房型名称')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每晚价格')),
                ('capacity', models.IntegerField(default=2, verbose_name='可住人数')),
                ('available_rooms', models.IntegerField(default=10, verbose_name='可用房间数')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='travel_app.hotel', verbose_name='酒店')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.roomtype', verbose_name='房型'),
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('economy', '经济舱'), ('premium', '超级经济舱'), ('business', '商务舱'), ('first', '头等舱')], default='economy', max_length=20, verbose_name='舱位类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('available_seats', models.IntegerField(default=50, verbose_name='可用座位')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='travel_app.flight', verbose_name='航班')),
            ],
            options={
                'verbose_name': '舱位',
                'verbose_name_plural': '舱位',
                'unique_together': {('flight', 'class_type')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_app.seatclass', verbose_name='舱位'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar_url', models.CharField(blank=True, max_length=500, verbose_name='头像URL')),
                ('preferred_currency', models.CharField(choices=[('CNY', '人民币 ¥'), ('USD', '美元 $'), ('EUR', '欧元 €')], default='CNY', max_length=3, verbose_name='偏好货币')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('package', '套餐'), ('hotel', '酒店'), ('flight', '航班'), ('destination', '目的地')], max_length=20, verbose_name='评价类型')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='晒图URL')),
                ('image', models.ImageField(blank=True, upload_to='reviews/', verbose_name='晒图')),
                ('is_approved', models.BooleanField(default=True, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.destination')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.hotel')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_app.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
                'ordering': ['-created_at'],
            },
        ),
    ]
