# Generated by Django 6.0.6 on 2026-07-08 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='航班号')),
                ('airline', models.CharField(max_length=50, verbose_name='航空公司')),
                ('departure', models.CharField(max_length=50, verbose_name='出发地')),
                ('destination', models.CharField(max_length=50, verbose_name='目的地')),
                ('departure_time', models.DateTimeField(verbose_name='出发时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('rating', models.FloatField(default=5.0, verbose_name='评分')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('destination', models.CharField(max_length=50, verbose_name='所在城市')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每晚价格')),
                ('rating', models.FloatField(default=5.0, verbose_name='评分')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
            ],
        ),
        migrations.CreateModel(
            name='TravelNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻/攻略标题')),
                ('category', models.CharField(choices=[('news', '实时新闻'), ('guide', '精选攻略')], default='news', max_length=10, verbose_name='分类')),
                ('summary', models.CharField(max_length=500, verbose_name='摘要（一句话简介）')),
                ('content', models.TextField(verbose_name='详细正文（支持富文本/长文）')),
                ('cover_url', models.URLField(default='https://images.unsplash.com/photo-1507525428034-b723cf961d3e', max_length=500, verbose_name='封面图链接')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='guidecomment',
            name='guide',
        ),
        migrations.AddField(
            model_name='guidecomment',
            name='bg_color',
            field=models.CharField(default='#007BFF', max_length=20, verbose_name='徽章背景色'),
        ),
        migrations.AddField(
            model_name='guidecomment',
            name='destination',
            field=models.CharField(default='', max_length=50, verbose_name='目的地'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidecomment',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=20, verbose_name='徽章文字色'),
        ),
        migrations.AddField(
            model_name='guidecomment',
            name='title',
            field=models.CharField(default=0, max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='guidecomment',
            name='content',
            field=models.TextField(verbose_name='评论正文'),
        ),
        migrations.AlterField(
            model_name='guidecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='guidecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('flight', '航班'), ('hotel', '酒店')], max_length=10, verbose_name='订单类型')),
                ('item_id', models.IntegerField(verbose_name='商品ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
