# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_flight_hotel_travelnews_remove_guidecomment_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecomment',
            name='guide',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='travel_app.guide',
                verbose_name='所属攻略',
            ),
        ),
    ]
