# Generated by Django 6.0.6 on 2026-07-09 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_userprofile_avatar_url_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100, verbose_name='套餐编号')),
                ('package_name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('destination', models.CharField(blank=True, max_length=100, verbose_name='目的地')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
                ('duration', models.CharField(max_length=50, verbose_name='行程天数')),
                ('hotel', models.CharField(blank=True, max_length=120, verbose_name='住宿')),
                ('transport', models.CharField(blank=True, max_length=120, verbose_name='交通')),
                ('meal', models.CharField(blank=True, max_length=160, verbose_name='餐饮/体验')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='套餐图片')),
                ('travelers', models.PositiveIntegerField(default=1, verbose_name='出行人数')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='出发日期')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('confirmed', '已预订'), ('cancelled', '已取消')], default='confirmed', max_length=20, verbose_name='状态')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='预订时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
