# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_guidefavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱地址')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(default='register', max_length=30, verbose_name='用途')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='套餐编号')),
                ('name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('destination', models.CharField(blank=True, max_length=100, verbose_name='目的地')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='图片链接')),
                ('fallback_image', models.CharField(blank=True, default='images/packages/p1.jpg', max_length=200, verbose_name='备用图片')),
                ('duration', models.CharField(max_length=50, verbose_name='行程天数')),
                ('hotel', models.CharField(blank=True, max_length=120, verbose_name='住宿')),
                ('transport', models.CharField(blank=True, max_length=120, verbose_name='交通')),
                ('meal', models.CharField(blank=True, max_length=160, verbose_name='餐饮/体验')),
                ('highlights', models.TextField(blank=True, default='', verbose_name='亮点')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='评价数')),
                ('is_featured', models.BooleanField(default=True, verbose_name='首页展示')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='头像地址')),
                ('preferred_currency', models.CharField(blank=True, default='CNY', max_length=3, verbose_name='偏好货币')),
                ('bio', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100, verbose_name='套餐编号')),
                ('package_name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('destination', models.CharField(blank=True, max_length=100, verbose_name='目的地')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
                ('duration', models.CharField(max_length=50, verbose_name='行程天数')),
                ('hotel', models.CharField(blank=True, max_length=120, verbose_name='住宿')),
                ('transport', models.CharField(blank=True, max_length=120, verbose_name='交通')),
                ('meal', models.CharField(blank=True, max_length=160, verbose_name='餐饮/体验')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='套餐图片')),
                ('travelers', models.PositiveIntegerField(default=1, verbose_name='出行人数')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='出发日期')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('confirmed', '已预订'), ('cancelled', '已取消')], default='confirmed', max_length=20, verbose_name='状态')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='预订时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
