# Generated by Django 6.0.6 on 2026-07-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Package ID')),
                ('name', models.CharField(max_length=200, verbose_name='Package name')),
                ('destination', models.CharField(blank=True, max_length=100, verbose_name='Destination')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='Image URL')),
                ('fallback_image', models.CharField(blank=True, default='images/packages/p1.jpg', max_length=200, verbose_name='Fallback image')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('hotel', models.CharField(blank=True, max_length=120, verbose_name='Hotel')),
                ('transport', models.CharField(blank=True, max_length=120, verbose_name='Transport')),
                ('meal', models.CharField(blank=True, max_length=160, verbose_name='Meal / experience')),
                ('highlights', models.TextField(blank=True, default='', verbose_name='Highlights')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Rating')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='Reviews')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Show on homepage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
    ]
